name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    container: debian:buster-slim
    
    strategy:
      fail-fast: false
      matrix:
        racket-version: ['7.1', '7.2', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8', 'current']
        variant: ['regular', 'CS']
        exclude:
        - racket-version: 7.1
          variant: 'CS'
        - racket-version: 7.2
          variant: 'CS'
        - racket-version: 7.3
          variant: 'CS'

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'minimal'
        variant: ${{ matrix.variant }}
        version: ${{ matrix.racket-version }}
        packages: 'redex', 'rackunit'
    - run: raco test main.rkt
